/* empty css                      */import{a as g,S as b,i as a}from"./assets/vendor-qRCtuz5G.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="https://pixabay.com/api/",S="55832000-3ddcf2f713b5877a9b0974dfc",v={key:S,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function w(o,t){return(await g.get(L,{params:{...v,q:o,page:t}})).data}const d=document.querySelector("#gallery"),p=document.querySelector(".gallery-actions .loader"),f=document.querySelector(".load-more-button"),P=new b("#gallery a",{captionsData:"alt",captionDelay:250});function E(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:h,downloads:y})=>`
        <li class="photo-card">
          <a class="photo-link" href="${n}">
            <img class="photo-image" src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes</b><span>${r}</span></p>
            <p><b>Views</b><span>${c}</span></p>
            <p><b>Comments</b><span>${h}</span></p>
            <p><b>Downloads</b><span>${y}</span></p>
          </div>
        </li>
      `).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}function q(){d.innerHTML=""}function $(){p.classList.add("is-visible")}function A(){p.classList.remove("is-visible")}function M(){f.classList.remove("is-hidden")}function l(){f.classList.add("is-hidden")}const R=document.querySelector("#search-form"),B=document.querySelector(".load-more-button"),C=document.querySelector("#gallery");let u="",i=1;const D=15;R.addEventListener("submit",O);B.addEventListener("click",_);async function O(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(!t){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}u=t,i=1,q(),l(),await m()}async function _(){i+=1,l(),await m(),x()}async function m(){$();try{const o=await w(u,i),t=Array.isArray(o.hits)?o.hits:[],s=Number(o.totalHits)||0;if(t.length===0){i===1?a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(l(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));return}E(t),i===1&&a.success({title:"Success",message:`Found ${s} images for "${u}".`,position:"topRight"});const n=Math.ceil(s/D);i>=n?(l(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M()}catch{a.error({title:"Error",message:"Unable to load images. Please try again later.",position:"topRight"})}finally{A()}}function x(){const o=C.querySelector(".photo-card");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
